#!/usr/bin/env python3
"""
Quick Chat Guide - Print instructions for chatting with Teams bot
"""

print("=" * 70)
print("💬 How to Chat with Teams Bot")
print("=" * 70)
print()
print("📋 Step-by-Step:")
print()
print("1️⃣  Start the bot (if not already running):")
print("   cd demos/03-teams")
print("   python test_teams_bot.py")
print()
print("2️⃣  Open Bot Framework Emulator")
print("   Download: https://github.com/Microsoft/BotFramework-Emulator/releases")
print()
print("3️⃣  Click 'Open Bot'")
print()
print("4️⃣  Enter Bot URL:")
print("   http://localhost:3978/api/messages")
print()
print("5️⃣  Leave App ID/Password EMPTY")
print()
print("6️⃣  Click 'Connect'")
print()
print("7️⃣  Start chatting!")
print()
print("=" * 70)
print("💬 Try These Commands:")
print("=" * 70)
print()
print("📊 Analytics:")
print('   "What was Q4 revenue?"')
print('   "Show me top 5 customers"')
print()
print("🔍 Search:")
print('   "search MCP tutorial"')
print('   "search how to create Genie space"')
print()
print("💰 Calculate:")
print('   "calculate 50000 Enterprise"')
print('   "calculate 25000 SMB"')
print()
print("⚙️ Commands:")
print("   /help")
print("   /reset")
print()
print("=" * 70)
print("📚 Full Guide: demos/03-teams/HOW_TO_CHAT.md")
print("=" * 70)

